version: 2

jobs:
  publish:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run : docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      - run : docker build -t $IMAGE_NAME:latest .
      - run : docker push $IMAGE_NAME:latest

workflows:
  version: 2

  ci:
    jobs:
      - publish